[tox]
envlist = 
  py312
  py311
  py310
  py39

[pytest]
minversion = 3
testpaths = tests
filterwarnings =
  ignore:please use dns\.resolver\.Resolver:DeprecationWarning
  ignore:pkg_resources is deprecated as an API:DeprecationWarning
  ignore:.*threading module.*:pytest.PytestUnraisableExceptionWarning

[testenv]
deps =
  -r requirements.txt
  pytest
  coverage
  mongomock>=4.1.0
commands =
	coverage run -m --omit="*/.tox/*,*/distutils/*,tests/*" pytest {posargs}
